### ISSUE TITLE
Archive fails with error "java.sql.SQLException: Result set after last row" when processing Type

### ISSUE THREAD

**Issue by joelthill** [sfa-siard/siard-suite#108]
I am trying to archive an oracle database. Processing fails with the following error message:

```
	  Routine: APLKN_ARCHV_ANLUX.FK_ASLH_PRFG_VE_INHLT_MUSS
	  Type: APLKN_ARCHV_ANLUX.TBS_VRZNG_ENHT
	ERROR [main] 17:24:04,312 ch.admin.bar.siard2.cmd.SiardFromDb Exception while downloading SIARD archive
	java.sql.SQLException: Result set after last row
	        at oracle.jdbc.driver.GeneratedScrollableResultSet.getString(GeneratedScrollableResultSet.java:879) ~[ojdbc6.jar:12.1.0.1.0]
	        at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:1460) ~[ojdbc6.jar:12.1.0.1.0]
	        at ch.admin.bar.siard2.cmd.MetaDataFromDb.createType(MetaDataFromDb.java:366) ~[siardcmd.jar:2.2.13]
	        at ch.admin.bar.siard2.cmd.MetaDataFromDb.getProcedureParameters(MetaDataFromDb.java:443) ~[siardcmd.jar:2.2.13]
	        at ch.admin.bar.siard2.cmd.MetaDataFromDb.getRoutines(MetaDataFromDb.java:865) ~[siardcmd.jar:2.2.13]
	        at ch.admin.bar.siard2.cmd.MetaDataFromDb.getSchemaMetaData(MetaDataFromDb.java:1150) ~[siardcmd.jar:2.2.13]
	        at ch.admin.bar.siard2.cmd.MetaDataFromDb.download(MetaDataFromDb.java:1254) ~[siardcmd.jar:2.2.13]
	        at ch.admin.bar.siard2.cmd.SiardFromDb.<init>(SiardFromDb.java:302) ~[siardcmd.jar:2.2.13]
	        at ch.admin.bar.siard2.cmd.SiardFromDb.main(SiardFromDb.java:371) [siardcmd.jar:2.2.13]
	  java.sql.SQLException: Result set after last row
```
A quick review of the context (the line starting with "Routine:") revealed that FK_ASLH_PRFG_VE_INHLT_MUSS is declared as:

```
CREATE OR REPLACE FUNCTION APLKN_ARCHV_ANLUX.FK_ASLH_PRFG_VE_INHLT_MUSS (
   pr_vrzng_enht IN TBS_VRZNG_ENHT%ROWTYPE
   )
RETURN INTEGER
```

My gut feeling tells me that the [%ROWTYPE](https://docs.oracle.com/cd/B13789_01/appdev.101/b10807/13_elems042.htm) type declaration (line starting with "Type: ") might be the cause of the issue. Other plain vanilla type declarations having been processed without any problems earlier in the process, I am wondering if SIARD is able to handle %ROWTYPE corrrectly?

cheers
j.

**Comment by joelthill** [comment]
Hi Max,
Pls let me know if I can help with logs or samples.
j.

**Comment by mburri** [comment]
@joelthill 
Sorry for the late response!

It's possible that `%rowtype` is not supported. We need to check this in detail. It would be really helpful if you could provide some sql to set up a minimal sample database to reproduce the problem.

Regarding Oracle databases: We usually use oracle 18-xe or oracle 21-xe.

Which version are you using?

**Comment by JohanSmolders** [comment]
I have the exact same issue when, in Oracle, a PL/SQL boolean is used in a routine and exporting the database.
First off, i want to point out that using a PL/SQL boolean in your database hits another bug i pointed out here: https://github.com/sfa-siard/JdbcBase/issues/7

I created a proposed fix in this pull-request: https://github.com/sfa-siard/JdbcBase/pull/8

I then created a patched version of jdbcbase.jar and tested again.

**Test scenario**

docker run -d --name SIARDDB -p 1521:1521 -e ORACLE_PWD=supersecret container-registry.oracle.com/database/express:21.3.0-xe

_Connect to PDB as system/supersecret and create a user (schema)_

jdbc:oracle:thin:@server.win.local:1521/XEPDB1

CREATE USER SIARDTEST
IDENTIFIED by SIARDTEST
ACCOUNT UNLOCK;
GRANT RESOURCE TO SIARDTEST;
GRANT CONNECT TO SIARDTEST;
ALTER USER SIARDTEST DEFAULT ROLE ALL;
ALTER USER SIARDTEST QUOTA UNLIMITED ON USERS;

_Create a table_

CONNECT SIARDTEST/SIARDTEST;

create table mytable(id number, descr varchar2(128));
insert into mytable(id, descr) values (1, 'HELLO WORLD');

_Create a function that uses a boolean_

CONNECT SIARDTEST/SIARDTEST;

CREATE OR REPLACE FUNCTION bool_to_string(p_bool BOOLEAN) RETURN VARCHAR2 IS
BEGIN
IF p_bool THEN
RETURN 'TRUE';
ELSE
RETURN 'FALSE';
END IF;
END;
/

Export the database

./siard-from-db -j=jdbc:oracle:thin:@server.local:1521/XEPDB1 -u=SYSTEM -p=supersecret -s=EXPORT_BOOLEAN.siard -e=EXPORT_BOOLEAN.xml

**This query** get 'PL/SQL Boolean' as typename, but it isn't a type name, it is a datatype.

SELECT
  NULL AS PROCEDURE_CAT,
  A.OWNER AS PROCEDURE_SCHEM,
  A.OBJECT_NAME AS PROCEDURE_NAME,
  A.ARGUMENT_NAME AS COLUMN_NAME,
  CASE
    WHEN A.POSITION = 0 THEN 5
    WHEN A.IN_OUT = 'IN' THEN 1
    WHEN A.IN_OUT = 'OUT' THEN 4
    WHEN A.IN_OUT = 'IN/OUT' THEN 2
    ELSE 0
  END AS COLUMN_TYPE,
  CASE
    WHEN T.TYPECODE = 'COLLECTION' THEN 2003
    WHEN A.DATA_TYPE = 'BLOB' THEN 2004
    WHEN A.DATA_TYPE = 'FLOAT' THEN 8
    WHEN A.DATA_TYPE = 'CHAR' THEN 1
    WHEN A.DATA_TYPE = 'RAW' THEN -3
    WHEN A.DATA_TYPE = 'NCHAR' THEN -15
    WHEN A.DATA_TYPE = 'XMLTYPE' THEN 2009
    WHEN A.DATA_TYPE = 'LONG RAW' THEN 2004
    WHEN A.DATA_TYPE LIKE 'INTERVAL%' THEN 1111
    WHEN A.DATA_TYPE = 'UROWID' THEN -8
    WHEN A.DATA_TYPE = 'TINYINT' THEN -6
    WHEN A.DATA_TYPE = 'INTEGER' THEN 4
    WHEN A.DATA_TYPE = 'LONG' THEN 2005
    WHEN A.DATA_TYPE = 'NCLOB' THEN 2011
    WHEN A.DATA_TYPE = 'NUMBER' THEN 2
    WHEN A.DATA_TYPE = 'NUMERIC' THEN 2
    WHEN T.TYPECODE = 'ANYDATA' THEN 2005
    WHEN A.DATA_TYPE = 'CLOB' THEN 2005
    WHEN A.DATA_TYPE = 'BIGINT' THEN -5
    WHEN A.DATA_TYPE = 'TIME' THEN 92
    WHEN A.DATA_TYPE LIKE 'TIMESTAMP%' THEN 93
    WHEN A.DATA_TYPE = 'BIT' THEN 16
    WHEN A.DATA_TYPE = 'VARCHAR2' THEN 12
    WHEN T.TYPECODE = 'OBJECT' THEN 2002
    WHEN A.DATA_TYPE = 'NVARCHAR2' THEN -9
    WHEN A.DATA_TYPE = 'DATE' THEN 93
    WHEN A.DATA_TYPE = 'BINARY_FLOAT' THEN 7
    WHEN A.DATA_TYPE = 'SMALLINT' THEN 5
    WHEN A.DATA_TYPE = 'DATALINK' THEN 2004
    WHEN A.DATA_TYPE = 'REAL' THEN 7
    WHEN A.DATA_TYPE = 'BFILE' THEN 2004
    WHEN A.DATA_TYPE = 'BINARY_DOUBLE' THEN 8
    WHEN A.DATA_TYPE = 'ROWID' THEN -8
    ELSE 1111
  END AS DATA_TYPE,
  **CASE 
    WHEN A.TYPE_OWNER IS NULL AND A.TYPE_NAME IS NULL THEN A.DATA_TYPE
    WHEN A.TYPE_OWNER IS NULL AND NOT A.TYPE_NAME IS NULL THEN '"' || A.TYPE_NAME || '"'
    ELSE '"' || A.TYPE_OWNER || '"."' || A.TYPE_NAME || '"'
  END AS TYPE_NAME,**
  CASE 
    WHEN A.DATA_PRECISION IS NULL THEN CASE 
      WHEN A.DATA_TYPE = 'NUMBER' THEN 38 
      ELSE A.DATA_LENGTH
    END    ELSE A.DATA_PRECISION
  END AS PRECISION,
  A.DATA_LENGTH AS LENGTH,
  A.DATA_SCALE AS SCALE,
  A.RADIX AS RADIX,
  2 AS NULLABLE,
  NULL AS REMARKS,
  A.DEFAULT_VALUE AS COLUMN_DEF,
  CAST(NULL AS NUMBER) AS SQL_DATA_TYPE,
  CAST(NULL AS NUMBER) AS SQL_DATETIME_SUB,
  A.DATA_LENGTH AS CHAR_OCTET_LENGTH,
  A.POSITION AS ORDINAL_POSITION,
  NULL AS IS_NULLABLE,  CASE
    WHEN P.PROCEDURE_NAME IS NULL THEN P.OBJECT_NAME
    ELSE P.PROCEDURE_NAME || '.' || P.OBJECT_NAME
  END AS SPECIFIC_NAME
FROM ALL_OBJECTS O
  INNER JOIN ALL_PROCEDURES P
  ON (O.OWNER = P.OWNER AND 
      O.OBJECT_NAME = P.OBJECT_NAME AND
      O.OBJECT_ID = P.OBJECT_ID)
  INNER JOIN ALL_ARGUMENTS A
  ON (O.OWNER = A.OWNER AND 
      O.OBJECT_NAME = A.OBJECT_NAME AND
      O.OBJECT_ID = A.OBJECT_ID)
  LEFT JOIN ALL_TYPES T
  ON (A.TYPE_NAME = T.TYPE_NAME AND
      A.TYPE_OWNER = T.OWNER)
WHERE
A.DATA_LEVEL = 0
AND A.OWNER LIKE 'SIARDTEST' ESCAPE '/'
AND A.OBJECT_NAME LIKE 'BOOL/_TO/_STRING' ESCAPE '/'

Then it launches this query which **yields 0 records.**  
(If you crash at this point apply patch https://github.com/sfa-siard/JdbcBase/pull/8)

SELECT
NULL as TYPE_CAT,
T.OWNER as TYPE_SCHEM,
T.TYPE_NAME AS TYPE_NAME,
NULL as CLASS_NAME,
2002 as DATA_TYPE,
NULL as REMARKS,
NULL as BASE_TYPE
FROM ALL_TYPES T
WHERE T.TYPE_NAME LIKE 'PL//SQL BOOLEAN' ESCAPE '/'
 AND (T.TYPECODE = 'OBJECT' OR T.TYPECODE = 'ANYDATA')

Next the following query is launched and the error is thrown:

SELECT
NULL as TYPE_CAT,
T.OWNER as TYPE_SCHEM,
T.TYPE_NAME AS TYPE_NAME,
NULL as CLASS_NAME,
2002 as DATA_TYPE,
NULL as REMARKS,
NULL as BASE_TYPE
FROM ALL_TYPES T
WHERE T.TYPE_NAME LIKE 'PL//SQL BOOLEAN' ESCAPE '/'
 AND T.OWNER LIKE 'SIARDTEST' ESCAPE '/'
 AND (T.TYPECODE = 'OBJECT' OR T.TYPECODE = 'ANYDATA')

ORDER BY DATA_TYPE, TYPE_CAT, TYPE_SCHEM, TYPE_NAME
Feb 18, 2025 1:08:48 PM ch.enterag.utils.logging.IndentLogger log
FINEST: << ch.admin.bar.siard2.jdbc.OracleDatabaseMetaData.getUDTs(oracle.jdbc.driver.ForwardOnlyResultSet@2aac8ad7)
ERROR [main] 13:08:48,907 ch.admin.bar.siard2.cmd.SiardFromDb Exception while downloading SIARD archive
java.sql.SQLException: Result set after last row
	at oracle.jdbc.driver.GeneratedScrollableResultSet.getString(GeneratedScrollableResultSet.java:879) ~[ojdbc6.jar:12.1.0.1.0]
	at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:1460) ~[ojdbc6.jar:12.1.0.1.0]
	at ch.admin.bar.siard2.cmd.MetaDataFromDb.createType(MetaDataFromDb.java:366) ~[siardcmd.jar:2.2.13]
	at ch.admin.bar.siard2.cmd.MetaDataFromDb.getProcedureParameters(MetaDataFromDb.java:443) ~[siardcmd.jar:2.2.13]
	at ch.admin.bar.siard2.cmd.MetaDataFromDb.getRoutines(MetaDataFromDb.java:865) ~[siardcmd.jar:2.2.13]
	at ch.admin.bar.siard2.cmd.MetaDataFromDb.getSchemaMetaData(MetaDataFromDb.java:1150) ~[siardcmd.jar:2.2.13]
	at ch.admin.bar.siard2.cmd.MetaDataFromDb.download(MetaDataFromDb.java:1254) ~[siardcmd.jar:2.2.13]
	at ch.admin.bar.siard2.cmd.SiardFromDb.<init>(SiardFromDb.java:302) ~[siardcmd.jar:2.2.13]
	at ch.admin.bar.siard2.cmd.SiardFromDb.main(SiardFromDb.java:371) [siardcmd.jar:2.2.13]
  java.sql.SQLException: Result set after last row

**Comment by llorentelemmc** [comment]
@JohanSmolders Thank you for your submission. We will look into this as soon as possible.

**Comment by mburri** [comment]
@JohanSmolders 
Thanks for your work!

Just to be sure, you've created jdbcbase.jar and patched your siard suite installation, and then the problem was solved? 

I think the most valuable point of your PR is that it reveals some underlying problems in the siard project itself. Since jdbcbase.jar is also used in jdbcposgres, jdbcoracle, jdbcmssql and others, all these projects need to be rebuilt as well. 

However, this is not your problem. We need to discuss the various options on how to proceed from here. 
For now we have to do the integration manually... this will take some time.

**Comment by JohanSmolders** [comment]
I zoomed in on the code a bit further.

The query launched is:

SELECT
NULL as TYPE_CAT,
T.OWNER as TYPE_SCHEM,
T.TYPE_NAME AS TYPE_NAME,
NULL as CLASS_NAME,
2002 as DATA_TYPE,
NULL as REMARKS,
NULL as BASE_TYPE
FROM ALL_TYPES T
WHERE T.TYPE_NAME LIKE 'PL//SQL BOOLEAN' ESCAPE '/'
AND T.OWNER LIKE 'SIARDTEST' ESCAPE '/'
AND (T.TYPECODE = 'OBJECT' OR T.TYPECODE = 'ANYDATA')


Then this code is executed.

rs.next();
                if (qiType.getName().equals(rs.getString("TYPE_NAME")) && qiType.getSchema()
                                                                                .equals(rs.getString("TYPE_SCHEM"))) {
                    String sRemarks = rs.getString("REMARKS");
                    if (sRemarks != null) mt.setDescription(sRemarks);
                    BaseSqlFactory bsf = new BaseSqlFactory();
                    PredefinedType pt = bsf.newPredefinedType();
                    int iBaseType = rs.getInt("BASE_TYPE");
                    if (iBaseType != Types.NULL) {
                        mt.setCategory(CategoryType.DISTINCT.value());
                        pt.initialize(iBaseType, iPrecision, iScale);
                        mt.setBase(pt.format());
                    } else {
                        mt.setCategory(CategoryType.UDT.value());
                        getAttributes(mt);
                    }
                } else throw new SQLException("Invalid type meta data found!");

The "if" checks if the owner and type is correct, otherwise it throws a SQLExeception. But considering the SQL launched, the SQLException can not be thrown since the same check is done in the where clause.  So, rs.next() will fail because no line is found OR the "if" will always be true.

Unfortunately I don't know what should happen in this case, since PL/SQL Boolean is a database specific type.

**Comment by joelthill** [comment]
@mburri : here we go for the construction of an as-simple-as-it-gets scenario :

1. table

```
DROP TABLE SIARD_POC.MY_TABLE CASCADE CONSTRAINTS;
CREATE TABLE SIARD_POC.MY_TABLE
(
  MY_COLUMN  NUMBER
)
TABLESPACE SIARD_POC_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;
```

2. function

```
CREATE OR REPLACE FUNCTION SIARD_POC.MY_PROBLEM_FUNCTION (my_row IN MY_TABLE%ROWTYPE)
    RETURN NUMBER
IS
BEGIN
    RETURN my_row.MY_COLUMN;
END MY_PROBLEM_FUNCTION;
/
```

that's it.
if you now `siard-from-db` this, you'll hopefully ultimately end up with the expected :

```
[..]
Routine: SIARD_POC.MY_PROBLEM_FUNCTION
  Type: SIARD_POC.MY_TABLE
ERROR [main] 15:46:53,722 ch.admin.bar.siard2.cmd.SiardFromDb Exception while downloading SIARD archive
java.sql.SQLException: Result set after last row
        at oracle.jdbc.driver.GeneratedScrollableResultSet.getString(GeneratedScrollableResultSet.java:879) ~[ojdbc6.jar:12.1.0.1.0]
        at oracle.jdbc.driver.GeneratedResultSet.getString(GeneratedResultSet.java:1460) ~[ojdbc6.jar:12.1.0.1.0]
        at ch.admin.bar.siard2.cmd.MetaDataFromDb.createType(MetaDataFromDb.java:366) ~[siardcmd.jar:2.2.13]
        at ch.admin.bar.siard2.cmd.MetaDataFromDb.getProcedureParameters(MetaDataFromDb.java:443) ~[siardcmd.jar:2.2.13]
        at ch.admin.bar.siard2.cmd.MetaDataFromDb.getRoutines(MetaDataFromDb.java:865) ~[siardcmd.jar:2.2.13]
        at ch.admin.bar.siard2.cmd.MetaDataFromDb.getSchemaMetaData(MetaDataFromDb.java:1150) ~[siardcmd.jar:2.2.13]
        at ch.admin.bar.siard2.cmd.MetaDataFromDb.download(MetaDataFromDb.java:1254) ~[siardcmd.jar:2.2.13]
        at ch.admin.bar.siard2.cmd.SiardFromDb.<init>(SiardFromDb.java:302) ~[siardcmd.jar:2.2.13]
        at ch.admin.bar.siard2.cmd.SiardFromDb.main(SiardFromDb.java:371) [siardcmd.jar:2.2.13]
  java.sql.SQLException: Result set after last row
```

hope this help

cheers
j.

**Comment by joelthill** [comment]
hi,

is there anything I can do to provide additional help or examples for the initial issue?
I see that #108 has been mentioned and referenced above, but I am unable to evaluate if it is worth testing the latest release for a fix? please advise.

cheers
j.
