### ISSUE TITLE
Table actions has no columns! - SIARD-Suite Version 2.2.147 and MySQL 8.0.23

### ISSUE THREAD

**Issue by TK1244** [sfa-siard/siard-suite#98]
I tried different Databases to archive with the SIARD-Suite V2.2.147 (wich should include a fix for this Exception, as far as i know) but i always get this error:

java.sql.SQLException: Table actions has no columns!
	at ch.admin.bar.siard2.cmd.MetaDataFromDb.getColumns(MetaDataFromDb.java:1120)
	at ch.admin.bar.siard2.cmd.MetaDataFromDb.getTables(MetaDataFromDb.java:1189)
	at ch.admin.bar.siard2.cmd.MetaDataFromDb.download(MetaDataFromDb.java:1252)
	at ch.admin.bar.siardsuite.service.database.DatabaseLoadService$DatabaseLoadTask.call(DatabaseLoadService.java:70)
	at ch.admin.bar.siardsuite.service.database.DatabaseLoadService$DatabaseLoadTask.call(DatabaseLoadService.java:46)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javafx.concurrent.Service.lambda$null$6(Service.java:725)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$7(Service.java:724)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

![image](https://github.com/sfa-siard/siard-suite/assets/145114256/2e65ffec-5d0d-4178-a07b-f6aabf72dfef)

 What can I do?

Thank you in Advance.
Tim

**Comment by mburri** [comment]
@TK1244 
We just tried to reproduce your issue without success.

Do you use a dedicated user that only has access to the schema that you want to archive? If not, try this first.

Otherwise, you could try to help us to reproduce the issue!
What OS do you use?
Which distribution of the SIARD Suite do you use? A native installer?

Could you provide the DDL script for the table "actions"? - is there anything special about it?

**Comment by TK1244** [comment]
I tried now a dedicate user; with no luck. Same error.

OS: Windows Server 2022 Standard 
![image](https://github.com/sfa-siard/siard-suite/assets/145114256/3e2c00ab-f4a2-4df3-bdd8-ddf258acfa93)

Java - Open JDK 64-Bit Corretto 1.8.0_382
JavaFX21
![image](https://github.com/sfa-siard/siard-suite/assets/145114256/cd5704b3-9b34-4466-8385-82e77807e468)

I used this Version:
https://github.com/sfa-siard/siard-suite/releases/download/v2.2.147/SIARD-Suite-v2.2.147.zip

I am using the "SIARD-Suite.bat" and in Line 36 the Options i had set a "@rem", so that siard-suite could start.
![image](https://github.com/sfa-siard/siard-suite/assets/145114256/1cc4e90c-da8d-47cc-860b-c83144e38b91)
Otherwise it was not possible to start.

The definition for the table actions:
[table actions.txt](https://github.com/sfa-siard/siard-suite/files/15402601/table.actions.txt)


Thank you in advance.
Best Regards.
